---
- name: assignment 9
  hosts: all
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  vars:
    administrator_name: corpadmin
  tasks:
  - name: Create a user with the value of the administrator_name variable on each system with a password
    user: name=administrator_name password='password'
  - name: Update all the current software packages on the system
    yum: name=* state=latest

- name: install and configure nginx
  hosts: web1
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: install nginx
    yum: name=nginx state=latest
  - name: copy file to system directory
    tamplet: 
    src: /default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  - lineinfile:
    dest: /etc/nginx/conf.d/default.conf
    regexp: 'ansible_fqdn'
    line: '10.0.0.147'
- name: install and configure mysql
  hosts: database1
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: install mysql
    yum: name=msqld state=latest 
 - name:  create 5 directories
    file:
    path: "{{ item }}"
    state: directory
    with_items:
      -'/var/data/client1'
      -'/var/data/client2'
      -'/var/data/client3'
      -'/var/data/client4'
      -'/var/data/client5'
