properties([pipelineTriggers([githubPush()])])
node('linux') {

    stage('Setup') {
          git credentialsId: 'GitHub_Credentials',
          url: 'https://github.com/UST-SEIS665/hw11-seis665-01-spring2019-AhmedAlgo.git'
          sh 'aws s3 cp s3://ahmed-algo-assignment-4/classweb.html ${WORKSPACE}/index.html'
          }
          

    
    stage('Build') {
        sh 'docker build -t classweb:1.0 .'
    }
    
    stage('Test') {
        sh 'docker run -d --name classweb1 -p 80:80 --env NGINX_PORT=80 classweb:1.0'
        sh "curl http://\$(docker inspect --format '{{ .NetworkSettings.IPAddress}}' classweb1)"
        
        sh 'docker stop classweb1'
        sh 'docker rm --force classweb1'
    }
    
}



